RentWeb/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rent.DataAccess.Repository.IRepository;
using Rent.Utility;

namespace RentWeb.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _hostEnvironment;

		public OrderController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		[HttpGet]
		[Authorize]
		public IActionResult Get(string? status = null)
		{
			var OrderHeaderList = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser");

			if (status == "cancelled")
			{
				OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusCancelled);
			}
			else
			{
				if (status == "completed")
				{
					OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusCompleted);
				}
				else
				{
					if (status == "inProcess")
					{
						OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusInProcess);
					}
					else
					{
						if (status == "ready")
						{
							OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusReady);
						}
						else
						{
							if (status == "issued")
							{
								OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusIssued);
							}
							else
							{
								if (status == "returned")
								{
									OrderHeaderList = OrderHeaderList.Where(u => u.Status == StaticDetails.StatusReturned);
								}
							}
						}
					}
				}
			}
			return Json(new { data = OrderHeaderList });
		}
	}
}

RentWeb/Pages/Admin/Order/ManageOrder.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;
using Rent.Models.ViewModel;
using Rent.Utility;

namespace RentWeb.Pages.Admin.Order
{
    [Authorize(Roles = $"{StaticDetails.AdminRole},{StaticDetails.RepairManRole}")]
    public class ManageOrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public List<OrderDetailVM> OrderDetailVM { get; set; }

        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public void OnGet()
        {
            OrderDetailVM = new();

            List<OrderHeader> orderHeaders = _unitOfWork.OrderHeader.GetAll(u => 
			u.Status == StaticDetails.StatusConfirmed ||
			u.Status == StaticDetails.StatusInProcess ||
			u.Status == StaticDetails.StatusReady ||
			u.Status == StaticDetails.StatusIssued).ToList();

            foreach (OrderHeader item in orderHeaders)
            {
                OrderDetailVM individaul = new OrderDetailVM()
                {
                    OrderHeader = item,
                    OrderDetails = _unitOfWork.OrderDetail.GetAll(u => u.OrderId == item.Id).ToList()
                };
                OrderDetailVM.Add(individaul);
            }
        }

		public IActionResult OnPostOrderInProcess(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusInProcess);
			_unitOfWork.Save();
			return RedirectToPage("ManageOrder");
		}

		public IActionResult OnPostOrderReady(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusReady);
			_unitOfWork.Save();
			return RedirectToPage("ManageOrder");
		}

		public IActionResult OnPostOrderIssue(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusIssued);
			_unitOfWork.Save();
			return RedirectToPage("ManageOrder");
		}

		public IActionResult OnPostOrderReturn(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusReturned);
			_unitOfWork.Save();
			return RedirectToPage("ManageOrder");
		}

		public IActionResult OnPostOrderCancel(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusCancelled);
			_unitOfWork.Save();
			return RedirectToPage("ManageOrder");
		}
	}
}

RentWeb/Pages/Admin/Order/OrderDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;
using Rent.Models.ViewModel;
using Rent.Utility;

namespace RentWeb.Pages.Admin.Order
{
	public class OrderDetailsModel : PageModel
	{
		private readonly IUnitOfWork _unitOfWork;

		public OrderDetailVM OrderDetailVM { get; set; }

		public OrderDetailsModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public void OnGet(int id)
		{
			OrderDetailVM = new()
			{
				OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == id, includeProperties: "ApplicationUser"),
				OrderDetails = _unitOfWork.OrderDetail.GetAll(u=>u.OrderId== id).ToList()
			};
		}

		public IActionResult OnPostOrderCompleted(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusCompleted);
			_unitOfWork.Save();
			return RedirectToPage("OrderList");
		}

		public IActionResult OnPostOrderCancel(int orderId)
		{
			_unitOfWork.OrderHeader.UpdateStatus(orderId, StaticDetails.StatusCancelled);
			_unitOfWork.Save();
			return RedirectToPage("OrderList");
		}
	}
}

RentWeb/Pages/Admin/Order/OrderList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RentWeb.Pages.Admin.Order
{
    public class OrderListModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RentWeb/Pages/Admin/Order/ManageOrder.cshtml
@page
@model RentWeb.Pages.Admin.Order.ManageOrderModel
@using Rent.Utility


<h1 class="text-primary py-3"><b>Управление заказами</b></h1>
<form method="post">
	<div class="container row bg-white p-2 mb-3 rounded">
		@foreach (var item in Model.OrderDetailVM)
		{
			<div class="col-12 pb-3 pt-3 mt-4 border rounded">
				<div class="row">
					<div class="col-4">
						Номер заказа : @item.OrderHeader.Id
						<ul class="text-info">
							@foreach (var details in item.OrderDetails)
							{
								<li>@details.Name x @details.Count</li>
							}
						</ul>
					</div>
					<div class="col-4 pb-2">
						<div class="input-group pb-2">
							<div class="input-group-append">
								<span class="input-group-text border">Время</span>
							</div>
							<input type="text" value="@item.OrderHeader.PickUpTime" class="form-control" readonly />
						</div>
						<textarea readonly asp-for="@item.OrderHeader.Comments" class="rounded border form-control" rows="3"></textarea>
					</div>
					<div class="col-3 offset-1 d-flex align-content-center">
						<div class="col-12">
							@if (item.OrderHeader.Status == StaticDetails.StatusConfirmed)
							{
								<button type="submit" class="btn btn-warning form-control mb-3"
								asp-page-handler="OrderInProcess" asp-route-orderId="@item.OrderHeader.Id">
									<i class="bi bi-tools"></i> &nbsp; Подготовка инструмента
								</button>
							}
							@if (item.OrderHeader.Status == StaticDetails.StatusInProcess)
							{
								<button type="submit" class="btn btn-success form-control mb-3"
								asp-page-handler="OrderReady" asp-route-orderId="@item.OrderHeader.Id">
									<i class="bi bi-hand-thumbs-up"></i> &nbsp; Инструмент готов к выдаче
								</button>
							}
							@if (item.OrderHeader.Status == StaticDetails.StatusReady)
							{
								<button type="submit" class="btn btn-info form-control mb-3"
								asp-page-handler="OrderIssue" asp-route-orderId="@item.OrderHeader.Id">
									<i class="bi bi-cart-check"></i> &nbsp; Инструмент выдан
								</button>
							}
							@if (item.OrderHeader.Status == StaticDetails.StatusIssued)
							{
								<button type="submit" class="btn btn-warning form-control mb-3"
								asp-page-handler="OrderReturn" asp-route-orderId="@item.OrderHeader.Id">
									<i class="bi bi-emoji-laughing"></i> &nbsp; Инструмент возращен
								</button>
							}

							<button type="submit" class="btn btn-outline-danger form-control mb-3"
								asp-page-handler="OrderCancel" asp-route-orderId="@item.OrderHeader.Id">
								<i class="bi bi-x-square-fill"></i> &nbsp; Отменить заказ
							</button>

						</div>
					</div>
				</div>
			</div>
		}
	</div>
</form>

RentWeb/Pages/Admin/Order/OrderDetails.cshtml
@page
@model RentWeb.Pages.Admin.Order.OrderDetailsModel
@using Rent.Utility

<form method="post">
	<div class="border p-4 ml-1 backgroundWhite mt-4">
		<div class="row pb-1">
			<div class="col-12 col-md-6 ">
				<p class="h2  text-primary">Подробно о заказе</p>
			</div>
			<div class="col-12 col-md-4 offset-md-2">
				<a asp-page="/Admin/Order/OrderList" class="btn btn-outline-primary form-control">Назад к заказам</a>
			</div>
		</div>
		<hr />
		<div class="row pt-2">
			<div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">

				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Имя
					</div>
					<div class="col-md-9 col-12">
						<input asp-for="OrderDetailVM.OrderHeader.PickupName" disabled class="form-control" />
					</div>
				</div>
				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Е-майл
					</div>
					<div class="col-md-9 col-12">
						<input asp-for="OrderDetailVM.OrderHeader.ApplicationUser.Email" disabled class="form-control" />
					</div>
				</div>
				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Номер телефона
					</div>
					<div class="col-md-9 col-12">
						<input asp-for="OrderDetailVM.OrderHeader.PhoneNumber" disabled class="form-control" />
					</div>
				</div>
				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Полная стоимость заказа
					</div>
					<div class="col-md-9 col-12">
						<input disabled asp-for="OrderDetailVM.OrderHeader.OrderTotal" class="form-control" />
					</div>
				</div>
				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Дата и время выдачи инструмента
					</div>
					<div class="col-md-9 col-12">
						<input value="@Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderDetailVM.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
					</div>
				</div>
				<div class="form-group row py-1">
					<div class="col-md-3 col-12 text-primary">
						Комментарии
					</div>
					<div class="col-md-9 col-12">
						<textarea asp-for="OrderDetailVM.OrderHeader.Comments" disabled class="form-control" rows="3"></textarea>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-12">
				<button type="submit" disabled class="btn btn-outline-info form-control">@Model.OrderDetailVM.OrderHeader.Status</button>

				<h4 class="d-flex justify-content-between align-content-center mb-3 pt-3">
					<span class="text-muted">Выбранный инструмент: </span>
					<span class="badge badge-secondary badge-pill">@Model.OrderDetailVM.OrderHeader.Id</span>
				</h4>
				<ul class="list-group mb-3">
					@foreach (var detail in Model.OrderDetailVM.OrderDetails)
					{

						<li class="list-group-item d-flex justify-content-between">
							<div>
								<h6 class="my-0">@detail.Name</h6>
								<small class="text-muted">Количество : @detail.Count</small>
							</div>
							<span class="text-muted">$@(detail.Price * detail.Count)</span>
						</li>
					}
					<li class="list-group-item d-flex justify-content-between bg-light">
						<span class="text-info"> Всего (руб)</span>
						<strong class="text-info">$@Model.OrderDetailVM.OrderHeader.OrderTotal</strong>
					</li>
				</ul>
				<div class="row pt-3">
					@if (Model.OrderDetailVM.OrderHeader.Status == StaticDetails.StatusReturned
							&& (User.IsInRole(StaticDetails.AdminRole) || User.IsInRole(StaticDetails.RepairManRole)))
					{
						<div class="col-12 pb-2">
							<button type="submit" class="btn btn-warning form-control"
								asp-page-handler="OrderCompleted" asp-route-orderId="@Model.OrderDetailVM.OrderHeader.Id">
								Завершить заказ
							</button>
						</div>
					}
					@if ((User.IsInRole(StaticDetails.AdminRole) || User.IsInRole(StaticDetails.StoreKeeperRole)) &&
							(Model.OrderDetailVM.OrderHeader.Status == StaticDetails.StatusInProcess ||
							Model.OrderDetailVM.OrderHeader.Status == StaticDetails.StatusReady ||
							Model.OrderDetailVM.OrderHeader.Status == StaticDetails.StatusIssued ||
							Model.OrderDetailVM.OrderHeader.Status == StaticDetails.StatusReturned
							))
					{
						<div class="col-12">
							<button type="submit" class="btn btn-outline-danger form-control"
								asp-page-handler="OrderCancel" asp-route-orderId="@Model.OrderDetailVM.OrderHeader.Id">
								<i class="bi bi-x-square"></i> &nbsp; Отменить заказ
							</button>
						</div>
					}
				</div>
			</div>
		</div>
	</div>
</form>

RentWeb/Pages/Admin/Order/OrderList.cshtml
@page
@model RentWeb.Pages.Admin.Order.OrderListModel

@{
	var status = HttpContext.Request.Query["status"];
	var cancelled = "text-primary";
	var completed = "text-primary";
	var inProcess = "text-primary";
	var ready = "text-primary";
	var issued = "text-primary";
	var returned = "text-primary";


	if (status == "cancelled")
	{
		cancelled = "active text-white";
	}
	else
	{
		if (status == "completed")
		{
			completed = "active text-white";
		}
		else
		{
			if (status == "inProcess")
			{
				inProcess = "active text-white";
			}
			else
			{
				if (status == "ready")
				{
					ready = "active text-white";
				}
				else
				{
					if (status == "issued")
					{
						issued = "active text-white";
					}
					else
					{
						if (status == "returned")
						{
							returned = "active text-white";
						}
					}
				}
			}
		}
	}
}

<div class="container p-3">
	<div class="d-flex justify-content-between">
		<div class="p-2">
			<h2 class="text-primary"><b>Перечень заказов</b></h2>
		</div>
		<div class="p-2">
			<ul class="list-group list-group-horizontal-sm">
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="cancelled">
				<li class="list-group-item @cancelled">Отменено</li>
				</a>
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="completed">
				<li class="list-group-item @completed">Завершено</li>
				</a>
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="inProcess">
				<li class="list-group-item @inProcess">Подготовка инструмента</li>
				</a>
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="ready">
				<li class="list-group-item @ready">Готов к выдаче</li>
				</a>
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="issued">
				<li class="list-group-item @issued">Выдан</li>
				</a>
				<a style="text-decoration:none;" asp-page="OrderList" asp-route-status="returned">
				<li class="list-group-item @returned">Возвращен</li>
				</a>
			</ul>
		</div>
	</div>

	<br /><br />

	<table id="DT_load" class=" table table-bordered table-striped" style="width=100%">
		<thead>
			<tr>
				<th>Id Заказа</th>
				<th>Имя</th>
				<th>Е-майл</th>
				<th>Общая стоимость заказа</th>
				<th>Время выдачи</th>
				<th></th>
			</tr>
		</thead>

	</table>
</div>

@section Scripts{
	<script src="~/js/orderlist.js"></script>
}