RentWeb/Pages/Customer/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;
using System.Security.Claims;

namespace RentWeb.Pages.Customer.Cart
{
	[Authorize]
	public class IndexModel : PageModel
	{
		public IEnumerable<ShoppingCart> ShoppingCartList { get; set; }

		public double CartTotal { get; set; }
		private readonly IUnitOfWork _unitOfWork;

		public IndexModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
			CartTotal = 0;
		}
		public void OnGet()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
					includeProperties: "CatalogItem,CatalogItem.PowerType,CatalogItem.Category");

				foreach (var cartItem in ShoppingCartList)
				{
					CartTotal += (cartItem.CatalogItem.Price * cartItem.Count);
				}
			}
		}

		public IActionResult OnPostPlus(int cartId)
		{
			var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
			_unitOfWork.ShoppingCart.IncrementCount(cart, 1);
			return RedirectToPage("/Customer/Cart/Index");
		}

		public IActionResult OnPostMinus(int cartId)
		{
			var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
			if (cart.Count == 1)
			{
				_unitOfWork.ShoppingCart.Remove(cart);
				_unitOfWork.Save();
			}
			else
			{
				_unitOfWork.ShoppingCart.DecrementCount(cart, 1);

			}

			return RedirectToPage("/Customer/Cart/Index");
		}

		public IActionResult OnPostRemove(int cartId)
		{
			var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(u => u.Id == cartId);
			_unitOfWork.ShoppingCart.Remove(cart);
			_unitOfWork.Save();
			return RedirectToPage("/Customer/Cart/Index");
		}
	}
}

RentWeb/Pages/Customer/Cart/Summary.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;
using Rent.Utility;
using System.Security.Claims;

namespace RentWeb.Pages.Customer.Cart
{
	[Authorize]
	[BindProperties]
	public class SummaryModel : PageModel
	{
		public IEnumerable<ShoppingCart> ShoppingCartList { get; set; }

		public OrderHeader OrderHeader { get; set; }
		private readonly IUnitOfWork _unitOfWork;

		public SummaryModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
			OrderHeader = new OrderHeader();
		}
		public void OnGet()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
					includeProperties: "CatalogItem,CatalogItem.PowerType,CatalogItem.Category");

				foreach (var cartItem in ShoppingCartList)
				{
					OrderHeader.OrderTotal += (cartItem.CatalogItem.Price * cartItem.Count);
				}
				ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);
				OrderHeader.PickupName = applicationUser.FirstName + " " + applicationUser.LastName;
				OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
			}
		}

		public void OnPost()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				ShoppingCartList = _unitOfWork.ShoppingCart.GetAll(filter: u => u.ApplicationUserId == claim.Value,
					includeProperties: "CatalogItem,CatalogItem.PowerType,CatalogItem.Category");

				foreach (var cartItem in ShoppingCartList)
				{
					OrderHeader.OrderTotal += (cartItem.CatalogItem.Price * cartItem.Count);
				}

				OrderHeader.Status = StaticDetails.StatusConfirmed;
				OrderHeader.OrderDate = System.DateTime.Now;
				OrderHeader.UserId = claim.Value;
				OrderHeader.PickUpTime = Convert.ToDateTime(OrderHeader.PickUpDate.ToShortDateString() + " " + 
					OrderHeader.PickUpTime.ToShortTimeString());
				_unitOfWork.OrderHeader.Add(OrderHeader);
				_unitOfWork.Save();

				foreach (var item in ShoppingCartList)
				{
					OrderDetails orderDetails = new()
					{
						CatalogItemId = item.CatalogItemId,
						OrderId = OrderHeader.Id,
						Name = item.CatalogItem.Name,
						Price = item.CatalogItem.Price,
						Count = item.Count
					};
					_unitOfWork.OrderDetail.Add(orderDetails);
				}

				_unitOfWork.ShoppingCart.RemoveRange(ShoppingCartList);
				_unitOfWork.Save();
			}
		}

	}
}

RentWeb/Pages/Customer/Home/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace RentWeb.Pages.Customer.Home
{
	[Authorize]
	public class DetailsModel : PageModel
	{
		private readonly IUnitOfWork _unitOfWork;

		public DetailsModel(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		[BindProperty]
		public ShoppingCart ShoppingCart { get; set; }


		public void OnGet(int id)
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			ShoppingCart = new()
			{
				ApplicationUserId = claim.Value,
				CatalogItem = _unitOfWork.CatalogItem.GetFirstOrDefault(u => u.Id == id, includeProperties: "Category,PowerType"),
				CatalogItemId = id
			};

		}

		public IActionResult OnPost()
		{
			if (ModelState.IsValid)
			{
				ShoppingCart shoppingCartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(
					filter: u => u.ApplicationUserId == ShoppingCart.ApplicationUserId &&
					u.CatalogItemId == ShoppingCart.CatalogItemId);
				if (shoppingCartFromDb == null)
				{
                    _unitOfWork.ShoppingCart.Add(ShoppingCart);
                    _unitOfWork.Save();
                }
				else
				{
					_unitOfWork.ShoppingCart.IncrementCount(shoppingCartFromDb, ShoppingCart.Count);
				}
				return RedirectToPage("Index");
			}
			return Page();
		}
	}
}

RentWeb/Pages/Customer/Home/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rent.DataAccess.Repository.IRepository;
using Rent.Models;

namespace RentWeb.Pages.Customer.Home
{
    public class IndexModel : PageModel
    {

        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IEnumerable<CatalogItem> CatalogItemList { get; set; }
        public IEnumerable<Category> CategoryList { get; set; }


        public void OnGet()
        {
            CatalogItemList = _unitOfWork.CatalogItem.GetAll(includeProperties: "Category,PowerType");
            CategoryList = _unitOfWork.Category.GetAll(orderby: u=> u.OrderBy(c=> c.DisplayOrder));
        }
    }
}

RentWeb/Pages/Customer/Cart/Index.cshtml
@page
@model RentWeb.Pages.Customer.Cart.IndexModel

<form method="post">
	<br />
	@if (Model.ShoppingCartList.Count()==0)
	{
		<div>
			Пожалуйста, добавьте арендуемые инструменты в корзину!
		</div>
	}
	else
	{
		<div class="container">
			<div class="card">
				<div class="card-header bg-dark text-light ml-0 ">
					<div class="row">
						<div class="col-6 pt-2">
							Корзина с арендуемым инструментом
						</div>
						<div class="col-6 text-end">
							<a href="~/Customer/Home/Index" class="btn btn-outline-light btn-sm">Продолжить выбор инструмента</a>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach (var item in Model.ShoppingCartList)
					{
						<div class="row">
							<div class="d-none d-lg-block col-lg-2 text-center py-2">
								<img src="@item.CatalogItem.ImageUrl" class="rounded" width="120" height="80" />
							</div>
							<div class="col-12 text-sm-center text-md-start col-md-5 pt-md-4 ">
								<h4><strong>@item.CatalogItem.Name</strong></h4>

								<div class="badge bg-primary text-center" style="font-size:12px;">
									@item.CatalogItem.Category.Name
								</div>
								<div class="badge bg-info text-center" style="font-size:12px;">
									@item.CatalogItem.PowerType.Name
								</div>
							</div>
							<div class="col-12 text-sm-center col-md-5 text-md-start row pt-3">
								<div class="col-4 text-md-right pt-md-3" style="padding-top:5px;">
									<h6><strong>$@item.CatalogItem.Price <span class="text-muted">x</span> @item.Count </strong></h6>
								</div>
								<div class="col-6 col-sm-4 col-lg-6">
									<button type="submit" class="btn btn-warning"
											asp-page-handler="plus" asp-route-cartId="@item.Id">
										<i class="bi bi-plus-square"></i>
									</button>
									<button type="submit" class="btn btn-secondary"
											asp-page-handler="minus" asp-route-cartId="@item.Id">
										<i class="bi bi-dash-square"></i>
									</button>
								</div>
								<div class="col-2 col-sm-4 col-lg-2 text-right">
									<button type="submit" class="btn btn-outline-danger"
											asp-page-handler="remove" asp-route-cartId="@item.Id">
										<i class="bi bi-trash-fill"></i>
									</button>
								</div>
							</div>
						</div>
						<hr />
					}
					<div class="row">
						<div class="col-12 col-md-5">
						</div>
						<div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
							<ul class="list-group">
								<li class="list-group-item d-flex justify-content-between bg-light">
									<span class="text-info"> Всего (Руб.)</span>
									<strong class="text-info">@Model.CartTotal</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="card-footer">
					<div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
						<a asp-page="Summary" class="btn btn-warning form-control">Перейти к оформлению заказа инструмента</a>
					</div>
				</div>
			</div>
		</div>
	}
</form>

RentWeb/Pages/Customer/Cart/Summary.cshtml
@page
@model RentWeb.Pages.Customer.Cart.SummaryModel
<form method="post">
	<br />
	<div class="backgroundWhiteBorder">
		<div class="container">
			<div class="card">
				<div class="card-header bg-dark text-light ml-0 ">
					<div class="row">
						<div class="col-6 pt-2">
							<h3 class="text-white-50">Сводная информация о заказе</h3>
						</div>
						<div class="col-6 text-end">
							<a asp-page="Index" class="btn btn-outline-light btn-sm">Назад к корзине</a>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="container rounded p-2">
						<div class="row">
							<div class="col-12 col-lg-6 pb-4">
								<div class="row">
									<h4 class="d-flex justify-content-between align-items-center mb-3">
										<span class="text-info">Данные о выдаче заказа:</span>
									</h4>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Имя</label>
									</div>
									<div class="col-9">
										<input asp-for="OrderHeader.PickupName" class="form-control" />
										<span asp-validation-for="OrderHeader.PickupName" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Телефон</label>
									</div>
									<div class="col-9">
										<input asp-for="OrderHeader.PhoneNumber" class="form-control" />
										<span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Дата выдачи</label>
									</div>
									<div class="col-9">
										<input value="" asp-for="OrderHeader.PickUpDate" type="date" class="form-control" />
										<span asp-validation-for="OrderHeader.PickUpDate" class="text-danger"></span>

									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Время выдачи</label>
									</div>
									<div class="col-9">
										<input value="" asp-for="OrderHeader.PickUpTime" type="time" class="form-control" />
										<span asp-validation-for="OrderHeader.PickUpTime" class="text-danger"></span>
									</div>
								</div>
								<div class="row my-1">
									<div class="col-3">
										<label>Дополнительная информация: </label>
									</div>
									<div class="col-9">
										<textarea asp-for="OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
									</div>
								</div>
							</div>

							<div class="col-12 col-lg-5 offset-lg-1">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Сводная информация о заказе:</span>
								</h4>
								<ul class="list-group mb-3">
									@foreach (var detail in Model.ShoppingCartList)
									{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@detail.CatalogItem.Name</h6>
											<small class="text-muted">Quantity: @detail.Count</small>
										</div>
											<span class="text-muted">$@(detail.CatalogItem.Price * @detail.Count)</span>
									</li>
									}
									<li class="list-group-item d-flex justify-content-between bg-light">
										<small class="text-info">Всего (Руб.)</small>
										<strong class="text-info">$@Model.OrderHeader.OrderTotal</strong>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="card-footer">
					<div class="row">
						<div class="col-12 col-md-4 offset-md-8">
							<button type="submit" id="btnPlaceOrder" value="Place Order" class="btn btn-warning form-control">Оформить заказ</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}